import { ExerciseDefinition } from './types/transformation';

export const transformationExercises: ExerciseDefinition[] = [
  // --- CHEST ---
  { id: 'chest_barbell_bench_press', name: 'Barbell Bench Press', muscleGroup: 'Chest', pattern: 'horizontal_push', difficulty: 5, requiredEquipment: ['barbell', 'gym'] },
  { id: 'chest_incline_barbell_press', name: 'Incline Barbell Press', muscleGroup: 'Chest', pattern: 'horizontal_push', difficulty: 5, requiredEquipment: ['barbell', 'gym'] },
  { id: 'chest_decline_bench_press', name: 'Decline Bench Press', muscleGroup: 'Chest', pattern: 'horizontal_push', difficulty: 5, requiredEquipment: ['barbell', 'gym'] },
  { id: 'chest_dumbbell_bench_press', name: 'Dumbbell Bench Press', muscleGroup: 'Chest', pattern: 'horizontal_push', difficulty: 4, requiredEquipment: ['dumbbells'] },
  { id: 'chest_incline_dumbbell_press', name: 'Incline Dumbbell Press', muscleGroup: 'Chest', pattern: 'horizontal_push', difficulty: 4, requiredEquipment: ['dumbbells'] },
  { id: 'chest_decline_dumbbell_press', name: 'Decline Dumbbell Press', muscleGroup: 'Chest', pattern: 'horizontal_push', difficulty: 4, requiredEquipment: ['dumbbells'] },
  { id: 'chest_machine_chest_press', name: 'Machine Chest Press', muscleGroup: 'Chest', pattern: 'horizontal_push', difficulty: 3, requiredEquipment: ['gym'] },
  { id: 'chest_push_up', name: 'Push Up', muscleGroup: 'Chest', pattern: 'horizontal_push', difficulty: 2, requiredEquipment: ['bodyweight'] },
  { id: 'chest_incline_push_up', name: 'Incline Push Up', muscleGroup: 'Chest', pattern: 'horizontal_push', difficulty: 2, requiredEquipment: ['bodyweight'] },
  { id: 'chest_decline_push_up', name: 'Decline Push Up', muscleGroup: 'Chest', pattern: 'horizontal_push', difficulty: 3, requiredEquipment: ['bodyweight'] },
  { id: 'chest_weighted_push_up', name: 'Weighted Push Up', muscleGroup: 'Chest', pattern: 'horizontal_push', difficulty: 4, requiredEquipment: ['bodyweight'] },
  { id: 'chest_chest_fly', name: 'Chest Fly', muscleGroup: 'Chest', pattern: 'chest_isolation', difficulty: 3, requiredEquipment: ['dumbbells'] },
  { id: 'chest_dumbbell_fly', name: 'Dumbbell Fly', muscleGroup: 'Chest', pattern: 'chest_isolation', difficulty: 3, requiredEquipment: ['dumbbells'] },
  { id: 'chest_cable_fly', name: 'Cable Fly', muscleGroup: 'Chest', pattern: 'chest_isolation', difficulty: 4, requiredEquipment: ['cables', 'gym'] },
  { id: 'chest_pec_deck_fly', name: 'Pec Deck Fly', muscleGroup: 'Chest', pattern: 'chest_isolation', difficulty: 2, requiredEquipment: ['gym'] },
  { id: 'chest_single_arm_cable_fly', name: 'Single Arm Cable Fly', muscleGroup: 'Chest', pattern: 'chest_isolation', difficulty: 4, requiredEquipment: ['cables', 'gym'] },
  { id: 'chest_chest_dips', name: 'Chest Dips', muscleGroup: 'Chest', pattern: 'horizontal_push', difficulty: 5, requiredEquipment: ['bodyweight', 'gym'] },
  { id: 'chest_smith_machine_bench_press', name: 'Smith Machine Bench Press', muscleGroup: 'Chest', pattern: 'horizontal_push', difficulty: 4, requiredEquipment: ['gym'] },

  // --- BACK ---
  { id: 'back_deadlift', name: 'Deadlift', muscleGroup: 'Back', pattern: 'hinge', difficulty: 8, requiredEquipment: ['barbell', 'gym'] },
  { id: 'back_lat_pulldown', name: 'Lat Pulldown', muscleGroup: 'Back', pattern: 'vertical_pull', difficulty: 3, requiredEquipment: ['cables', 'gym'] },
  { id: 'back_wide_grip_lat_pulldown', name: 'Wide Grip Lat Pulldown', muscleGroup: 'Back', pattern: 'vertical_pull', difficulty: 3, requiredEquipment: ['cables', 'gym'] },
  { id: 'back_close_grip_lat_pulldown', name: 'Close Grip Lat Pulldown', muscleGroup: 'Back', pattern: 'vertical_pull', difficulty: 3, requiredEquipment: ['cables', 'gym'] },
  { id: 'back_pull_up', name: 'Pull Up', muscleGroup: 'Back', pattern: 'vertical_pull', difficulty: 6, requiredEquipment: ['bodyweight'] },
  { id: 'back_chin_up', name: 'Chin Up', muscleGroup: 'Back', pattern: 'vertical_pull', difficulty: 5, requiredEquipment: ['bodyweight'] },
  { id: 'back_assisted_pull_up', name: 'Assisted Pull Up', muscleGroup: 'Back', pattern: 'vertical_pull', difficulty: 3, requiredEquipment: ['gym'] },
  { id: 'back_bent_over_row', name: 'Bent Over Row', muscleGroup: 'Back', pattern: 'horizontal_pull', difficulty: 6, requiredEquipment: ['barbell', 'gym'] },
  { id: 'back_barbell_row', name: 'Barbell Row', muscleGroup: 'Back', pattern: 'horizontal_pull', difficulty: 6, requiredEquipment: ['barbell', 'gym'] },
  { id: 'back_t_bar_row', name: 'T-Bar Row', muscleGroup: 'Back', pattern: 'horizontal_pull', difficulty: 5, requiredEquipment: ['barbell', 'gym'] },
  { id: 'back_seated_cable_row', name: 'Seated Cable Row', muscleGroup: 'Back', pattern: 'horizontal_pull', difficulty: 3, requiredEquipment: ['cables', 'gym'] },
  { id: 'back_single_arm_dumbbell_row', name: 'Single Arm Dumbbell Row', muscleGroup: 'Back', pattern: 'horizontal_pull', difficulty: 4, requiredEquipment: ['dumbbells'] },
  { id: 'back_machine_row', name: 'Machine Row', muscleGroup: 'Back', pattern: 'horizontal_pull', difficulty: 3, requiredEquipment: ['gym'] },
  { id: 'back_straight_arm_pulldown', name: 'Straight Arm Pulldown', muscleGroup: 'Back', pattern: 'vertical_pull', difficulty: 3, requiredEquipment: ['cables', 'gym'] },
  { id: 'back_rack_pull', name: 'Rack Pull', muscleGroup: 'Back', pattern: 'hinge', difficulty: 7, requiredEquipment: ['barbell', 'gym'] },
  { id: 'back_hyperextension', name: 'Hyperextension', muscleGroup: 'Back', pattern: 'hinge', difficulty: 3, requiredEquipment: ['gym'] },

  // --- SHOULDERS ---
  { id: 'shoulder_overhead_press', name: 'Overhead Press', muscleGroup: 'Shoulders', pattern: 'vertical_push', difficulty: 6, requiredEquipment: ['barbell', 'gym'] },
  { id: 'shoulder_seated_dumbbell_press', name: 'Seated Dumbbell Press', muscleGroup: 'Shoulders', pattern: 'vertical_push', difficulty: 4, requiredEquipment: ['dumbbells'] },
  { id: 'shoulder_arnold_press', name: 'Arnold Press', muscleGroup: 'Shoulders', pattern: 'vertical_push', difficulty: 5, requiredEquipment: ['dumbbells'] },
  { id: 'shoulder_machine_shoulder_press', name: 'Machine Shoulder Press', muscleGroup: 'Shoulders', pattern: 'vertical_push', difficulty: 3, requiredEquipment: ['gym'] },
  { id: 'shoulder_lateral_raise', name: 'Lateral Raise', muscleGroup: 'Shoulders', pattern: 'shoulder_isolation', difficulty: 3, requiredEquipment: ['dumbbells'] },
  { id: 'shoulder_cable_lateral_raise', name: 'Cable Lateral Raise', muscleGroup: 'Shoulders', pattern: 'shoulder_isolation', difficulty: 3, requiredEquipment: ['cables', 'gym'] },
  { id: 'shoulder_front_raise', name: 'Front Raise', muscleGroup: 'Shoulders', pattern: 'shoulder_isolation', difficulty: 2, requiredEquipment: ['dumbbells'] },
  { id: 'shoulder_rear_delt_fly', name: 'Rear Delt Fly', muscleGroup: 'Shoulders', pattern: 'shoulder_isolation', difficulty: 3, requiredEquipment: ['dumbbells'] },
  { id: 'shoulder_reverse_pec_deck', name: 'Reverse Pec Deck', muscleGroup: 'Shoulders', pattern: 'shoulder_isolation', difficulty: 2, requiredEquipment: ['gym'] },
  { id: 'shoulder_face_pull', name: 'Face Pull', muscleGroup: 'Shoulders', pattern: 'shoulder_isolation', difficulty: 3, requiredEquipment: ['cables', 'gym'] },
  { id: 'shoulder_upright_row', name: 'Upright Row', muscleGroup: 'Shoulders', pattern: 'vertical_pull', difficulty: 4, requiredEquipment: ['barbell', 'gym'] },
  { id: 'shoulder_landmine_press', name: 'Landmine Press', muscleGroup: 'Shoulders', pattern: 'vertical_push', difficulty: 4, requiredEquipment: ['barbell', 'gym'] },

  // --- BICEPS ---
  { id: 'bicep_barbell_curl', name: 'Barbell Curl', muscleGroup: 'Biceps', pattern: 'bicep_isolation', difficulty: 3, requiredEquipment: ['barbell', 'gym'] },
  { id: 'bicep_ez_bar_curl', name: 'EZ Bar Curl', muscleGroup: 'Biceps', pattern: 'bicep_isolation', difficulty: 3, requiredEquipment: ['barbell', 'gym'] },
  { id: 'bicep_dumbbell_curl', name: 'Dumbbell Curl', muscleGroup: 'Biceps', pattern: 'bicep_isolation', difficulty: 2, requiredEquipment: ['dumbbells'] },
  { id: 'bicep_alternating_dumbbell_curl', name: 'Alternating Dumbbell Curl', muscleGroup: 'Biceps', pattern: 'bicep_isolation', difficulty: 2, requiredEquipment: ['dumbbells'] },
  { id: 'bicep_hammer_curl', name: 'Hammer Curl', muscleGroup: 'Biceps', pattern: 'bicep_isolation', difficulty: 2, requiredEquipment: ['dumbbells'] },
  { id: 'bicep_cable_curl', name: 'Cable Curl', muscleGroup: 'Biceps', pattern: 'bicep_isolation', difficulty: 2, requiredEquipment: ['cables', 'gym'] },
  { id: 'bicep_preacher_curl', name: 'Preacher Curl', muscleGroup: 'Biceps', pattern: 'bicep_isolation', difficulty: 3, requiredEquipment: ['gym', 'barbell'] },
  { id: 'bicep_machine_curl', name: 'Machine Curl', muscleGroup: 'Biceps', pattern: 'bicep_isolation', difficulty: 2, requiredEquipment: ['gym'] },
  { id: 'bicep_concentration_curl', name: 'Concentration Curl', muscleGroup: 'Biceps', pattern: 'bicep_isolation', difficulty: 2, requiredEquipment: ['dumbbells'] },
  { id: 'bicep_spider_curl', name: 'Spider Curl', muscleGroup: 'Biceps', pattern: 'bicep_isolation', difficulty: 3, requiredEquipment: ['dumbbells'] },
  { id: 'bicep_incline_dumbbell_curl', name: 'Incline Dumbbell Curl', muscleGroup: 'Biceps', pattern: 'bicep_isolation', difficulty: 3, requiredEquipment: ['dumbbells'] },

  // --- TRICEPS ---
  { id: 'tricep_pushdown', name: 'Tricep Pushdown', muscleGroup: 'Triceps', pattern: 'tricep_isolation', difficulty: 2, requiredEquipment: ['cables', 'gym'] },
  { id: 'tricep_rope_pushdown', name: 'Rope Pushdown', muscleGroup: 'Triceps', pattern: 'tricep_isolation', difficulty: 2, requiredEquipment: ['cables', 'gym'] },
  { id: 'tricep_overhead_extension', name: 'Overhead Tricep Extension', muscleGroup: 'Triceps', pattern: 'tricep_isolation', difficulty: 3, requiredEquipment: ['dumbbells'] },
  { id: 'tricep_skull_crusher', name: 'Skull Crusher', muscleGroup: 'Triceps', pattern: 'tricep_isolation', difficulty: 4, requiredEquipment: ['barbell', 'gym'] },
  { id: 'tricep_close_grip_bench_press', name: 'Close Grip Bench Press', muscleGroup: 'Triceps', pattern: 'horizontal_push', difficulty: 5, requiredEquipment: ['barbell', 'gym'] },
  { id: 'tricep_bench_dips', name: 'Bench Dips', muscleGroup: 'Triceps', pattern: 'tricep_isolation', difficulty: 2, requiredEquipment: ['bodyweight'] },
  { id: 'tricep_parallel_bar_dips', name: 'Parallel Bar Dips', muscleGroup: 'Triceps', pattern: 'vertical_push', difficulty: 5, requiredEquipment: ['bodyweight', 'gym'] },
  { id: 'tricep_single_arm_cable_extension', name: 'Single Arm Cable Extension', muscleGroup: 'Triceps', pattern: 'tricep_isolation', difficulty: 3, requiredEquipment: ['cables', 'gym'] },
  { id: 'tricep_kickbacks', name: 'Kickbacks', muscleGroup: 'Triceps', pattern: 'tricep_isolation', difficulty: 2, requiredEquipment: ['dumbbells'] },
  { id: 'tricep_machine_extension', name: 'Machine Tricep Extension', muscleGroup: 'Triceps', pattern: 'tricep_isolation', difficulty: 2, requiredEquipment: ['gym'] },

  // --- LEGS ---
  { id: 'leg_barbell_squat', name: 'Barbell Squat', muscleGroup: 'Legs', pattern: 'squat', difficulty: 7, requiredEquipment: ['barbell', 'gym'] },
  { id: 'leg_front_squat', name: 'Front Squat', muscleGroup: 'Legs', pattern: 'squat', difficulty: 7, requiredEquipment: ['barbell', 'gym'] },
  { id: 'leg_hack_squat', name: 'Hack Squat', muscleGroup: 'Legs', pattern: 'squat', difficulty: 5, requiredEquipment: ['gym'] },
  { id: 'leg_smith_machine_squat', name: 'Smith Machine Squat', muscleGroup: 'Legs', pattern: 'squat', difficulty: 4, requiredEquipment: ['gym'] },
  { id: 'leg_press', name: 'Leg Press', muscleGroup: 'Legs', pattern: 'squat', difficulty: 4, requiredEquipment: ['gym'] },
  { id: 'leg_walking_lunges', name: 'Walking Lunges', muscleGroup: 'Legs', pattern: 'lunge', difficulty: 4, requiredEquipment: ['dumbbells'] },
  { id: 'leg_bulgarian_split_squat', name: 'Bulgarian Split Squat', muscleGroup: 'Legs', pattern: 'squat', difficulty: 6, requiredEquipment: ['dumbbells'] },
  { id: 'leg_goblet_squat', name: 'Goblet Squat', muscleGroup: 'Legs', pattern: 'squat', difficulty: 3, requiredEquipment: ['dumbbells'] },
  { id: 'leg_romanian_deadlift', name: 'Romanian Deadlift', muscleGroup: 'Legs', pattern: 'hinge', difficulty: 6, requiredEquipment: ['barbell', 'gym'] },
  { id: 'leg_stiff_leg_deadlift', name: 'Stiff Leg Deadlift', muscleGroup: 'Legs', pattern: 'hinge', difficulty: 5, requiredEquipment: ['barbell', 'gym'] },
  { id: 'leg_extension', name: 'Leg Extension', muscleGroup: 'Legs', pattern: 'leg_isolation', difficulty: 2, requiredEquipment: ['gym'] },
  { id: 'leg_curl', name: 'Leg Curl', muscleGroup: 'Legs', pattern: 'leg_isolation', difficulty: 2, requiredEquipment: ['gym'] },
  { id: 'leg_glute_bridge', name: 'Glute Bridge', muscleGroup: 'Legs', pattern: 'hinge', difficulty: 2, requiredEquipment: ['bodyweight'] },
  { id: 'leg_hip_thrust', name: 'Hip Thrust', muscleGroup: 'Legs', pattern: 'hinge', difficulty: 4, requiredEquipment: ['barbell', 'gym'] },
  { id: 'leg_standing_calf_raise', name: 'Standing Calf Raise', muscleGroup: 'Legs', pattern: 'leg_isolation', difficulty: 2, requiredEquipment: ['gym'] },
  { id: 'leg_seated_calf_raise', name: 'Seated Calf Raise', muscleGroup: 'Legs', pattern: 'leg_isolation', difficulty: 2, requiredEquipment: ['gym'] },

  // --- ABS & CORE ---
  { id: 'abs_crunch', name: 'Crunch', muscleGroup: 'Abs', pattern: 'core_flexion', difficulty: 1, requiredEquipment: ['bodyweight'] },
  { id: 'abs_cable_crunch', name: 'Cable Crunch', muscleGroup: 'Abs', pattern: 'core_flexion', difficulty: 3, requiredEquipment: ['cables', 'gym'] },
  { id: 'abs_decline_crunch', name: 'Decline Crunch', muscleGroup: 'Abs', pattern: 'core_flexion', difficulty: 3, requiredEquipment: ['gym'] },
  { id: 'abs_sit_up', name: 'Sit Up', muscleGroup: 'Abs', pattern: 'core_flexion', difficulty: 2, requiredEquipment: ['bodyweight'] },
  { id: 'abs_leg_raise', name: 'Leg Raise', muscleGroup: 'Abs', pattern: 'core_flexion', difficulty: 4, requiredEquipment: ['bodyweight'] },
  { id: 'abs_hanging_leg_raise', name: 'Hanging Leg Raise', muscleGroup: 'Abs', pattern: 'core_flexion', difficulty: 5, requiredEquipment: ['bodyweight', 'gym'] },
  { id: 'abs_reverse_crunch', name: 'Reverse Crunch', muscleGroup: 'Abs', pattern: 'core_flexion', difficulty: 3, requiredEquipment: ['bodyweight'] },
  { id: 'abs_russian_twist', name: 'Russian Twist', muscleGroup: 'Abs', pattern: 'core_iso', difficulty: 3, requiredEquipment: ['bodyweight'] },
  { id: 'abs_mountain_climber', name: 'Mountain Climber', muscleGroup: 'Abs', pattern: 'core_flexion', difficulty: 3, requiredEquipment: ['bodyweight'] },
  { id: 'abs_plank', name: 'Plank', muscleGroup: 'Abs', pattern: 'core_iso', difficulty: 2, requiredEquipment: ['bodyweight'] },
  { id: 'abs_side_plank', name: 'Side Plank', muscleGroup: 'Abs', pattern: 'core_iso', difficulty: 3, requiredEquipment: ['bodyweight'] },
  { id: 'abs_ab_wheel_rollout', name: 'Ab Wheel Rollout', muscleGroup: 'Abs', pattern: 'core_flexion', difficulty: 6, requiredEquipment: ['gym'] },
  { id: 'abs_bicycle_crunch', name: 'Bicycle Crunch', muscleGroup: 'Abs', pattern: 'core_flexion', difficulty: 3, requiredEquipment: ['bodyweight'] },

  // --- CARDIO ---
  { id: 'cardio_treadmill_walk', name: 'Treadmill Walk', muscleGroup: 'Cardio', pattern: 'cardio', difficulty: 1, requiredEquipment: ['gym'] },
  { id: 'cardio_treadmill_run', name: 'Treadmill Run', muscleGroup: 'Cardio', pattern: 'cardio', difficulty: 4, requiredEquipment: ['gym'] },
  { id: 'cardio_cycling', name: 'Cycling', muscleGroup: 'Cardio', pattern: 'cardio', difficulty: 3, requiredEquipment: ['gym'] },
  { id: 'cardio_stationary_bike', name: 'Stationary Bike', muscleGroup: 'Cardio', pattern: 'cardio', difficulty: 3, requiredEquipment: ['gym'] },
  { id: 'cardio_elliptical', name: 'Elliptical', muscleGroup: 'Cardio', pattern: 'cardio', difficulty: 2, requiredEquipment: ['gym'] },
  { id: 'cardio_rowing_machine', name: 'Rowing Machine', muscleGroup: 'Cardio', pattern: 'cardio', difficulty: 5, requiredEquipment: ['gym'] },
  { id: 'cardio_jump_rope', name: 'Jump Rope', muscleGroup: 'Cardio', pattern: 'cardio', difficulty: 4, requiredEquipment: ['bodyweight'] },
  { id: 'cardio_burpees', name: 'Burpees', muscleGroup: 'Cardio', pattern: 'cardio', difficulty: 6, requiredEquipment: ['bodyweight'] },
  { id: 'cardio_stair_climber', name: 'Stair Climber', muscleGroup: 'Cardio', pattern: 'cardio', difficulty: 4, requiredEquipment: ['gym'] },
  { id: 'cardio_swimming', name: 'Swimming', muscleGroup: 'Cardio', pattern: 'cardio', difficulty: 5, requiredEquipment: ['bodyweight'] },
  { id: 'cardio_jogging', name: 'Jogging', muscleGroup: 'Cardio', pattern: 'cardio', difficulty: 3, requiredEquipment: ['bodyweight'] },
  { id: 'cardio_sprint_intervals', name: 'Sprint Intervals', muscleGroup: 'Cardio', pattern: 'cardio', difficulty: 8, requiredEquipment: ['bodyweight'] },
];
